-- MoonTea — unified orders table (website + in-store)
--
-- One row per order. Both the website (source='online') and the iPad app
-- (source='pos') insert into this table. New rows default to print_status
-- 'pending'. The POS polls for pending website orders, atomically claims each
-- one, enqueues it to the receipt printer, and flips it to 'printed'.
-- Claiming = a conditional UPDATE that only succeeds while the row is still
-- 'pending', so two iPads never print the same order.
--
-- In-store sales are pushed as source='pos', print_status='printed' (they were
-- already printed at the till), so they never re-enter the queue.
--
-- Canonical copy: ios-order-app/supabase_schema.sql. See also
-- ios-order-app/docs/orders-schema-and-code-map.md for the per-column map of
-- which app files touch what.

create table if not exists public.orders (
    id             uuid primary key default gen_random_uuid(),
    source         text not null default 'online'
                     check (source in ('online', 'pos')),
    -- Human-facing order reference: "W-1042" (website) or "P-1043" (POS).
    -- Generated by next_order_code() below.
    order_number   text not null,
    created_at     timestamptz not null default now(),
    customer_name  text,
    customer_phone text,
    -- Line items as JSON:
    -- [{ "name": "Brown Sugar", "modifiers": ["Tapioca"],
    --    "unit_price": 8.00, "quantity": 2, "type": "Boba" }]
    -- `type` is web-only (it drives the boba/corndog station screens); the
    -- iOS decoder ignores unknown keys.
    items          jsonb not null default '[]'::jsonb,
    subtotal       numeric(10,2) not null default 0,
    tax            numeric(10,2) not null default 0,
    total          numeric(10,2) not null default 0,
    payment_method text not null default 'online',
    notes          text,
    -- Print lifecycle: 'pending' (not printed yet) -> 'printed'.
    print_status   text not null default 'pending'
                     check (print_status in ('pending', 'printed')),
    printed_at     timestamptz,
    printed_by     text
);

create index if not exists orders_pending_idx
    on public.orders (created_at)
    where print_status = 'pending';

create index if not exists orders_created_idx
    on public.orders (created_at desc);

-- ============================================================
-- Order codes
-- One global sequence shared by every client, so a website code (W-1042) and
-- an in-store code (P-1043) can never collide. nextval() is atomic, so no
-- advisory lock is needed — this replaces the old day-scoped max()+1
-- next_order_number(), which depended on the removed "orderNumber" and
-- "timestamp" columns.
-- ============================================================
create sequence if not exists public.order_number_seq start with 1000;

create or replace function public.next_order_code(prefix text)
returns text
language sql
volatile
as $$
    select prefix || '-' || nextval('public.order_number_seq')::text;
$$;

grant execute on function public.next_order_code(text) to anon;
grant usage, select on sequence public.order_number_seq to anon;

-- ============================================================
-- Row Level Security
-- Both clients call PostgREST with only the anon key (no user auth), so anon
-- needs explicit permissive policies. Tighten (e.g. scope by an API key or JWT
-- claim) before exposing the anon key beyond trusted staff devices.
-- ============================================================
alter table public.orders enable row level security;

drop policy if exists orders_anon_select on public.orders;
create policy orders_anon_select on public.orders for select to anon using (true);

drop policy if exists orders_anon_update on public.orders;
create policy orders_anon_update on public.orders for update to anon using (true) with check (true);

drop policy if exists orders_anon_insert on public.orders;
create policy orders_anon_insert on public.orders for insert to anon with check (true);
